/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 karita.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/karita.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.001']} position={[13.974, -0.069, -0.327]} rotation={[0, -Math.PI / 2, 0]} scale={[0.008, 0.013, 0.013]} />
      <mesh geometry={nodes.bind_9.geometry} material={materials.Binding} position={[13.973, -0.135, 1.526]} rotation={[-Math.PI, 0, 0]} scale={[0.026, 0.043, 0.029]} />
      <mesh geometry={nodes.base_3.geometry} material={materials.Base} position={[12.977, -0.15, 0.479]} scale={[0.016, 0.011, 0.014]} />
      <mesh geometry={nodes.base_4.geometry} material={materials.Binding} position={[14.327, 0.02, 0.216]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.027, 0.018, 0.018]} />
      <mesh geometry={nodes.body_1.geometry} material={materials.Body} position={[12.922, 0.085, -0.165]} rotation={[Math.PI / 2, -0.011, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.body_2.geometry} material={materials.Body} position={[13.696, 0.145, 0.669]} rotation={[Math.PI / 2, -0.011, 0]} scale={[0.025, 0.025, 0.015]} />
      <mesh geometry={nodes.body_5.geometry} material={materials.Body} position={[12.943, 0.151, 0.218]} rotation={[Math.PI / 2, -0.011, -Math.PI / 2]} scale={[0.012, 0.014, 0.015]} />
      <mesh geometry={nodes.base_4001.geometry} material={materials.Base} position={[14.342, 0.124, 0.684]} rotation={[Math.PI / 2, 0, 0]} scale={[0.025, 0.025, 0.006]} />
      <mesh geometry={nodes.bind_1.geometry} material={materials.Binding} position={[13.213, 0.582, 0.7]} scale={0.025} />
      <mesh geometry={nodes.body_3.geometry} material={materials.Body} position={[13.696, 0.145, -0.249]} rotation={[1.544, -0.011, 0]} scale={[0.025, 0.025, 0.015]} />
      <mesh geometry={nodes.body_4.geometry} material={materials.Body} position={[14.403, 0.113, -0.217]} rotation={[-1.581, 0, 0]} scale={[0.022, 0.022, 0.002]} />
      <mesh geometry={nodes.bind_3.geometry} material={materials.Binding} position={[13.184, 0.096, 0.684]} rotation={[Math.PI / 2, -0.219, 0]} scale={0.025} />
      <mesh geometry={nodes.bind_6.geometry} material={materials.Binding} position={[14.415, 0.03, 0.473]} rotation={[Math.PI / 2, 0, 0]} scale={[0.019, 0.027, 0.02]} />
      <mesh geometry={nodes.bind_10.geometry} material={materials.Binding} position={[13.973, -0.135, 0.654]} rotation={[-Math.PI, 0, 0]} scale={[0.026, 0.043, 0.029]} />
      <mesh geometry={nodes.wheel_1.geometry} material={materials.wheel} position={[13.973, -0.073, 0.695]} rotation={[Math.PI / 2, 0.521, 0]} scale={[0.005, 0.021, 0.005]} />
      <mesh geometry={nodes.wheel_7.geometry} material={materials.wheel} position={[13.973, -0.073, 0.753]} rotation={[Math.PI / 2, 0.001, 0]} scale={[0.025, 0.021, 0.025]} />
      <mesh geometry={nodes.wheel_011.geometry} material={materials.wheel} position={[13.973, -0.073, -0.252]} rotation={[Math.PI / 2, -0.522, Math.PI]} scale={[0.005, 0.021, 0.005]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[13.973, -0.072, 0.768]} rotation={[-Math.PI, -1.571, 0]} scale={[0.008, 0.013, 0.013]} />
      <mesh geometry={nodes.wood_stick_04.geometry} material={materials.Body} position={[12.919, 0.156, 0.701]} rotation={[1.614, -0.014, 1.613]} scale={[-0.008, -0.033, -0.009]} />
      <mesh geometry={nodes.wood_stick_04001.geometry} material={materials.Body} position={[12.923, 0.154, -0.285]} rotation={[-2.486, 0.004, -1.592]} scale={[-0.008, -0.033, -0.009]} />
    </group>
  )
}

useGLTF.preload('/karita.glb')
